package cardealershipapp.common.transfer;

/**
 *
 * @author Miroslav Kološnjaji
 */
public enum Operation {
    
    LOGIN,
    LOGOUT,
    EXIT,
    
    CITY_GET_ALL,
    CITY_FIND_BY_ID,
    
    BRAND_GET_ALL,
    BRAND_FIND_BY_ID,
    
    MODEL_ADD,
    MODEL_UPDATE,
    MODEL_DELETE,
    MODEL_DELETE_MULTI,
    MODEL_GET_ALL,
    MODEL_FIND_BY_ID,
    
    BUSINESSUNIT_GET_ALL,
    BUSINESSUNIT_FIND_BY_ID,
   
    VEHICLE_ADD,
    VEHICLE_UPDATE,
    VEHICLE_DELETE,
    VEHICLE_DELETE_MULTI,
    VEHICLE_DELETE_BY_VIN,
    VEHICLE_DELETE_MULTIPLE_BY_VIN,
    VEHICLE_GET_ALL,
    
    EQUIPMENT_ADD,
    EQUIPMENT_UPDATE,
    EQUIPMENT_DELETE,
    EQUIPMENT_DELETE_MULTI,
    EQUIPMENT_GET_ALL,
    
    CUSTOMER_ADD,
    CUSTOMER_UPDATE,
    CUSTOMER_DELETE,
    CUSTOMER_DELETE_MULTI,
    CUSTOMER_GET_ALL,
    
    PURCHASE_ORDER_ADD,
    PURCHASE_ORDER_UPDATE,
    PURCHASE_ORDER_DELETE,
    PURCHASE_ORDER_DELETE_MULTI,
    PURCHASE_ORDER_GET_ALL,
    PURCHASE_ORDER_FIND_BY_ID,
    
    PURCHASE_ORDER_ITEM_ADD,
    PURCHASE_ORDER_ITEM_UPDATE,
    PURCHASE_ORDER_ITEM_DELETE,
    PURCHASE_ORDER_ITEM_GET_ALL
    
}
