package cardealershipapp.client.ui.mainform;

import cardealershipapp.client.ui.mainform.ci.MainController;

import javax.swing.*;


/**
 * @author Miroslav Kološnjaji
 */
public class MainForm extends javax.swing.JFrame {

    private MainController mainController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLoggedUser;
    private javax.swing.JMenu menuControlPanel;
    private javax.swing.JMenuItem menuItemAllVehicles;
    private javax.swing.JMenuItem menuItemGetAllPurchaseOrders;
    private javax.swing.JMenuItem menuItemModel;
    private javax.swing.JMenuItem menuItemPurchaseOrder;
    private javax.swing.JMenuItem menuLogOffItem;
    private javax.swing.JMenu menuLogin;
    private javax.swing.JMenu menuProfile;
    private javax.swing.JMenu menuPurchase;
    private javax.swing.JMenu menuVehicle;
    public MainForm() {
        initComponents();
        initController();
    }

    private void initController() {
        this.mainController = new MainController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLoggedUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProfile = new javax.swing.JMenu();
        menuLogOffItem = new javax.swing.JMenuItem();
        menuVehicle = new javax.swing.JMenu();
        menuItemAllVehicles = new javax.swing.JMenuItem();
        menuPurchase = new javax.swing.JMenu();
        menuItemPurchaseOrder = new javax.swing.JMenuItem();
        menuItemGetAllPurchaseOrders = new javax.swing.JMenuItem();
        menuControlPanel = new javax.swing.JMenu();
        menuItemModel = new javax.swing.JMenuItem();
        menuLogin = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(20, 28, 28));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }

            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setForeground(new java.awt.Color(60, 63, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealershipapp/client/ui/resources/images/bmw_main.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLoggedUser, javax.swing.GroupLayout.DEFAULT_SIZE, 1599, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLoggedUser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE))
        );

        menuProfile.setText("Profil");
        menuProfile.setEnabled(false);

        menuLogOffItem.setText("Odjavi se");
        menuLogOffItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogOffItemMouseClicked(evt);
            }
        });
        menuLogOffItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogOffItemActionPerformed(evt);
            }
        });
        menuProfile.add(menuLogOffItem);

        jMenuBar1.add(menuProfile);

        menuVehicle.setText("Vozila");

        menuItemAllVehicles.setText("Pregled svih vozila");
        menuItemAllVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAllVehiclesActionPerformed(evt);
            }
        });
        menuVehicle.add(menuItemAllVehicles);

        jMenuBar1.add(menuVehicle);

        menuPurchase.setText("Prodaja");
        menuPurchase.setEnabled(false);

        menuItemPurchaseOrder.setText("Nova porudzbenica");
        menuItemPurchaseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPurchaseOrderActionPerformed(evt);
            }
        });
        menuPurchase.add(menuItemPurchaseOrder);

        menuItemGetAllPurchaseOrders.setText("Pregled svih porudzbenica");
        menuItemGetAllPurchaseOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGetAllPurchaseOrdersActionPerformed(evt);
            }
        });
        menuPurchase.add(menuItemGetAllPurchaseOrders);

        jMenuBar1.add(menuPurchase);

        menuControlPanel.setText("Kontrolni panel");
        menuControlPanel.setEnabled(false);

        menuItemModel.setText("Model");
        menuItemModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModelActionPerformed(evt);
            }
        });
        menuControlPanel.add(menuItemModel);

        jMenuBar1.add(menuControlPanel);

        menuLogin.setText("Prijavi se");
        menuLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLoginMouseClicked(evt);
            }
        });
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuLogin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAllVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAllVehiclesActionPerformed
        mainController.getVehicleSearchForm();
    }//GEN-LAST:event_menuItemAllVehiclesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        mainController.closingApplication();
    }//GEN-LAST:event_formWindowClosing

    private void menuItemModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModelActionPerformed
        mainController.getModelSearchForm();
    }//GEN-LAST:event_menuItemModelActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        mainController.availableOptions();
    }//GEN-LAST:event_formWindowActivated

    private void menuLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLoginMouseClicked
        mainController.logIn();
    }//GEN-LAST:event_menuLoginMouseClicked

    private void menuLogOffItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogOffItemMouseClicked

    }//GEN-LAST:event_menuLogOffItemMouseClicked

    private void menuLogOffItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogOffItemActionPerformed
        mainController.logOff();
    }//GEN-LAST:event_menuLogOffItemActionPerformed

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed

    }//GEN-LAST:event_menuLoginActionPerformed

    private void menuItemPurchaseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPurchaseOrderActionPerformed
        mainController.getPurchaseOrderCreateForm();
    }//GEN-LAST:event_menuItemPurchaseOrderActionPerformed

    private void menuItemGetAllPurchaseOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGetAllPurchaseOrdersActionPerformed
        mainController.getPurchaseOrderSearchForm();
    }//GEN-LAST:event_menuItemGetAllPurchaseOrdersActionPerformed
    // End of variables declaration//GEN-END:variables

    public JMenu getMenuProfile() {
        return menuProfile;
    }

    public JMenu getMenuPurchase() {
        return menuPurchase;
    }

    public JMenu getMenuControlPanel() {
        return menuControlPanel;
    }

    public JMenu getMenuLogin() {
        return menuLogin;
    }

    public JLabel getLblLoggedUser() {
        return lblLoggedUser;
    }

}
