package cardealershipapp.client.ui.purchaseorder;

import cardealershipapp.common.domain.PurchaseOrderItem;
import cardealershipapp.client.session.ApplicationSession;
import cardealershipapp.client.ui.purchaseorder.controller.PurchaseOrderEditController;
import cardealershipapp.client.ui.vehicle.VehicleSearchForm;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;

/**
 * @author Miroslav Kološnjaji
 */
public class PurchaseOrderEditForm extends javax.swing.JDialog {


    private final List<PurchaseOrderItem> purchaseOrderItems;
    private PurchaseOrderEditController purchaseOrderEditController;
    private LocalDate date;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnChoseVehicle;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnUpdatePurchaseOrder;
    private javax.swing.JComboBox<Object> comboItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEngineDisplacement;
    private javax.swing.JLabel lblPurchaseDate;
    private javax.swing.JLabel lblPurchaseOrderID;
    private javax.swing.JPanel pnlEquipmentInfo;
    private javax.swing.JPanel pnlItemInfo;
    private javax.swing.JPanel pnlVehicleInfo;
    private javax.swing.JPanel pnlVendorCustomerInfo;
    private javax.swing.JSpinner spinnerQuantity;
    private javax.swing.JTable tblItems;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerCompany;
    private javax.swing.JTextField txtCustomerEmail;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPhone;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSalesPersonName;
    private javax.swing.JTextField txtTotalPrice;
    private javax.swing.JTextField txtVehicleBodyType;
    private javax.swing.JTextField txtVehicleBrand;
    private javax.swing.JTextField txtVehicleEngineDispl;
    private javax.swing.JTextField txtVehicleEnginePow;
    private javax.swing.JTextField txtVehicleFuelType;
    private javax.swing.JTextField txtVehicleModel;
    private javax.swing.JTextField txtVehiclePrice;
    private javax.swing.JTextField txtVehicleVinNumber;
    private javax.swing.JTextField txtVehicleYearOfProduction;

    /**
     * Creates new form PurchaseOrderForm
     */
    public PurchaseOrderEditForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ApplicationSession.getInstance().setPurchaseOrderFormIsOpen(true);

        purchaseOrderItems = new ArrayList<>();
        initComponents();
        initController();
        prepareForm();


    }

    private void initController() {
        purchaseOrderEditController = new PurchaseOrderEditController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVendorCustomerInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSalesPersonName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCustomerEmail = new javax.swing.JTextField();
        txtCustomerPhone = new javax.swing.JTextField();
        txtCustomerAddress = new javax.swing.JTextField();
        txtCustomerCompany = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlVehicleInfo = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtVehicleBrand = new javax.swing.JTextField();
        txtVehicleModel = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtVehicleBodyType = new javax.swing.JTextField();
        txtVehicleYearOfProduction = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lblEngineDisplacement = new javax.swing.JLabel();
        txtVehicleEngineDispl = new javax.swing.JTextField();
        txtVehicleEnginePow = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtVehicleFuelType = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtVehiclePrice = new javax.swing.JTextField();
        btnChoseVehicle = new javax.swing.JButton();
        txtVehicleVinNumber = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        pnlEquipmentInfo = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        comboItem = new javax.swing.JComboBox<>();
        btnAddItem = new javax.swing.JButton();
        spinnerQuantity = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        pnlItemInfo = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        btnDeleteItem = new javax.swing.JButton();
        btnUpdatePurchaseOrder = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblPurchaseDate = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblPurchaseOrderID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }

            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlVendorCustomerInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("KUPAC");

        txtSalesPersonName.setEditable(false);

        jLabel3.setText("Ime i prezime: ");

        txtCompany.setEditable(false);
        txtCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyActionPerformed(evt);
            }
        });

        jLabel5.setText("Kompanija: ");

        jLabel6.setText("Adresa:");

        txtAddress.setEditable(false);

        txtPhone.setEditable(false);

        jLabel7.setText("Telefon:");

        txtEmail.setEditable(false);

        jLabel8.setText("Email:");

        jLabel4.setText("Ime i prezime: ");

        jLabel9.setText("Kompanija: ");

        jLabel10.setText("Adresa:");

        jLabel11.setText("Telefon:");

        jLabel12.setText("Email:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("PRODAVAC");

        javax.swing.GroupLayout pnlVendorCustomerInfoLayout = new javax.swing.GroupLayout(pnlVendorCustomerInfo);
        pnlVendorCustomerInfo.setLayout(pnlVendorCustomerInfoLayout);
        pnlVendorCustomerInfoLayout.setHorizontalGroup(
                pnlVendorCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlVendorCustomerInfoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlVendorCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlVendorCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(pnlVendorCustomerInfoLayout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtSalesPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(pnlVendorCustomerInfoLayout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(pnlVendorCustomerInfoLayout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(pnlVendorCustomerInfoLayout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(pnlVendorCustomerInfoLayout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlVendorCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlVendorCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(pnlVendorCustomerInfoLayout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(pnlVendorCustomerInfoLayout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtCustomerCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(pnlVendorCustomerInfoLayout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(pnlVendorCustomerInfoLayout.createSequentialGroup()
                                                        .addComponent(jLabel11)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(pnlVendorCustomerInfoLayout.createSequentialGroup()
                                                        .addComponent(jLabel12)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel2))
                                .addContainerGap())
        );
        pnlVendorCustomerInfoLayout.setVerticalGroup(
                pnlVendorCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlVendorCustomerInfoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlVendorCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlVendorCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtSalesPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlVendorCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtCustomerCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlVendorCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlVendorCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlVendorCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(txtCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))
                                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlVehicleInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("VOZILO");

        jLabel15.setText("Marka:");

        txtVehicleBrand.setEditable(false);

        txtVehicleModel.setEditable(false);

        jLabel16.setText("Model: ");

        jLabel17.setText("Karoserija:");

        txtVehicleBodyType.setEditable(false);

        txtVehicleYearOfProduction.setEditable(false);

        jLabel18.setText("Godina:            ");

        lblEngineDisplacement.setText("Zapremina motora:");

        txtVehicleEngineDispl.setEditable(false);

        txtVehicleEnginePow.setEditable(false);

        jLabel20.setText("Snaga motora (KW)");

        txtVehicleFuelType.setEditable(false);

        jLabel21.setText("Vrsta goriva:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("CENA VOZILA");

        txtVehiclePrice.setEditable(false);
        txtVehiclePrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtVehiclePrice.setForeground(new java.awt.Color(0, 153, 102));

        btnChoseVehicle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChoseVehicle.setText("IZABERI VOZILO");
        btnChoseVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoseVehicleActionPerformed(evt);
            }
        });

        txtVehicleVinNumber.setEditable(false);

        jLabel27.setText("Broj sasije:");

        javax.swing.GroupLayout pnlVehicleInfoLayout = new javax.swing.GroupLayout(pnlVehicleInfo);
        pnlVehicleInfo.setLayout(pnlVehicleInfoLayout);
        pnlVehicleInfoLayout.setHorizontalGroup(
                pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlVehicleInfoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlVehicleInfoLayout.createSequentialGroup()
                                                .addGroup(pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel16)
                                                        .addComponent(jLabel15)
                                                        .addComponent(jLabel17)
                                                        .addComponent(jLabel18))
                                                .addGap(18, 18, 18)
                                                .addGroup(pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtVehicleBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtVehicleModel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtVehicleBodyType, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtVehicleYearOfProduction, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel14)
                                        .addComponent(btnChoseVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addGroup(pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVehicleInfoLayout.createSequentialGroup()
                                                .addGroup(pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel20)
                                                        .addComponent(lblEngineDisplacement)
                                                        .addComponent(jLabel21))
                                                .addGap(18, 18, 18)
                                                .addGroup(pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtVehicleEngineDispl, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtVehicleEnginePow, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtVehicleFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVehicleInfoLayout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtVehiclePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVehicleInfoLayout.createSequentialGroup()
                                                .addComponent(jLabel27)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtVehicleVinNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        pnlVehicleInfoLayout.setVerticalGroup(
                pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlVehicleInfoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtVehicleBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15)
                                        .addComponent(lblEngineDisplacement)
                                        .addComponent(txtVehicleEngineDispl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtVehicleModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16)
                                        .addComponent(txtVehicleEnginePow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtVehicleBodyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17)
                                        .addComponent(txtVehicleFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtVehicleVinNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel27))
                                        .addGroup(pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtVehicleYearOfProduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel18)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlVehicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel22)
                                                .addComponent(txtVehiclePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnChoseVehicle))
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlEquipmentInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("OPREMA");

        comboItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Oprema"}));

        btnAddItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddItem.setText("DODAJ OPREMU");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        spinnerQuantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        spinnerQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("kolicina");

        javax.swing.GroupLayout pnlEquipmentInfoLayout = new javax.swing.GroupLayout(pnlEquipmentInfo);
        pnlEquipmentInfo.setLayout(pnlEquipmentInfoLayout);
        pnlEquipmentInfoLayout.setHorizontalGroup(
                pnlEquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlEquipmentInfoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlEquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23)
                                        .addComponent(comboItem, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlEquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlEquipmentInfoLayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel25)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(pnlEquipmentInfoLayout.createSequentialGroup()
                                                .addComponent(spinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        pnlEquipmentInfoLayout.setVerticalGroup(
                pnlEquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlEquipmentInfoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlEquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlEquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(comboItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAddItem))
                                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlItemInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlItemInfo.setToolTipText("");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("DODATNE STAVKE");

        tblItems.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblItems.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Redni broj", "Naziv", "Kolicina", "Cena", "Valuta"
                }
        ));
        jScrollPane2.setViewportView(tblItems);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("UKUPNO:");

        txtTotalPrice.setEditable(false);
        txtTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotalPrice.setForeground(new java.awt.Color(0, 153, 102));

        btnDeleteItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteItem.setText("OBRISI");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlItemInfoLayout = new javax.swing.GroupLayout(pnlItemInfo);
        pnlItemInfo.setLayout(pnlItemInfoLayout);
        pnlItemInfoLayout.setHorizontalGroup(
                pnlItemInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlItemInfoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlItemInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addGroup(pnlItemInfoLayout.createSequentialGroup()
                                                .addComponent(jLabel24)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(pnlItemInfoLayout.createSequentialGroup()
                                                .addComponent(btnDeleteItem)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        pnlItemInfoLayout.setVerticalGroup(
                pnlItemInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlItemInfoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pnlItemInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnDeleteItem)
                                        .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnUpdatePurchaseOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdatePurchaseOrder.setText("AZURIRAJ");
        btnUpdatePurchaseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePurchaseOrderActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel19.setText("PORUDZBENICA");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("DATUM:");
        jLabel26.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblPurchaseDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPurchaseDate.setForeground(new java.awt.Color(0, 153, 102));
        lblPurchaseDate.setToolTipText("");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setText("#");

        lblPurchaseOrderID.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPurchaseOrderID.setForeground(new java.awt.Color(0, 153, 102));
        lblPurchaseOrderID.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pnlItemInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlEquipmentInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlVehicleInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlVendorCustomerInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnUpdatePurchaseOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel28)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblPurchaseOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel26)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel26)
                                        .addComponent(lblPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel28)
                                        .addComponent(lblPurchaseOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlVendorCustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlVehicleInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlEquipmentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlItemInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdatePurchaseOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        purchaseOrderEditController.prepareForm();
        purchaseOrderEditController.prepareVehicleInfoFields();
    }


    private void txtCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyActionPerformed

    private void btnChoseVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoseVehicleActionPerformed
        JDialog vehicleSearchDialog = new VehicleSearchForm(null, true);
        vehicleSearchDialog.setLocationRelativeTo(this);
        vehicleSearchDialog.setVisible(true);
    }//GEN-LAST:event_btnChoseVehicleActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int answer = purchaseOrderEditController.confirmDialog("Promene nisu sacuvane, da li zelite da izadjete?", this);
        if (answer == JOptionPane.YES_OPTION) {
            ApplicationSession.getInstance().setOrderSelectedVehicle(null);
            ApplicationSession.getInstance().setPurchaseOrderFormIsOpen(false);
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        purchaseOrderEditController.activeForm();
        purchaseOrderEditController.activeFormVehicleInfoFields();

    }//GEN-LAST:event_formWindowActivated

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed

        purchaseOrderEditController.addItem();

    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed

        purchaseOrderEditController.deleteItem();

    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void btnUpdatePurchaseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePurchaseOrderActionPerformed

        purchaseOrderEditController.update();

    }//GEN-LAST:event_btnUpdatePurchaseOrderActionPerformed


    public LocalDate getDate() {
        return date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    public List<PurchaseOrderItem> getPurchaseOrderItems() {
        return purchaseOrderItems;
    }

    public JButton getBtnDeleteItem() {
        return btnDeleteItem;
    }


    public JComboBox<Object> getComboItem() {
        return comboItem;
    }


    public JLabel getLblEngineDisplacement() {
        return lblEngineDisplacement;
    }

    public JLabel getLblPurchaseDate() {
        return lblPurchaseDate;
    }

    public JLabel getLblPurchaseOrderID() {
        return lblPurchaseOrderID;
    }

    public JSpinner getSpinnerQuantity() {
        return spinnerQuantity;
    }

    public JTable getTblItems() {
        return tblItems;
    }

    public JTextField getTxtAddress() {
        return txtAddress;
    }

    public JTextField getTxtCompany() {
        return txtCompany;
    }

    public JTextField getTxtCustomerAddress() {
        return txtCustomerAddress;
    }

    public JTextField getTxtCustomerCompany() {
        return txtCustomerCompany;
    }

    public JTextField getTxtCustomerEmail() {
        return txtCustomerEmail;
    }

    public JTextField getTxtCustomerName() {
        return txtCustomerName;
    }

    public JTextField getTxtCustomerPhone() {
        return txtCustomerPhone;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public JTextField getTxtPhone() {
        return txtPhone;
    }

    public JTextField getTxtSalesPersonName() {
        return txtSalesPersonName;
    }

    public JTextField getTxtTotalPrice() {
        return txtTotalPrice;
    }

    public JTextField getTxtVehicleBodyType() {
        return txtVehicleBodyType;
    }

    public JTextField getTxtVehicleBrand() {
        return txtVehicleBrand;
    }

    public JTextField getTxtVehicleEngineDispl() {
        return txtVehicleEngineDispl;
    }

    public JTextField getTxtVehicleEnginePow() {
        return txtVehicleEnginePow;
    }

    public JTextField getTxtVehicleFuelType() {
        return txtVehicleFuelType;
    }

    public JTextField getTxtVehicleModel() {
        return txtVehicleModel;
    }

    public JTextField getTxtVehiclePrice() {
        return txtVehiclePrice;
    }

    public JTextField getTxtVehicleVinNumber() {
        return txtVehicleVinNumber;
    }

    public JTextField getTxtVehicleYearOfProduction() {
        return txtVehicleYearOfProduction;
    }
}
