CREATE DATABASE IF NOT EXISTS CarDelership_DB
	DEFAULT CHARACTER SET utf8mb4    
	COLLATE utf8mb4_sl_0900_ai_ci;

USE CarDelership_DB;

CREATE TABLE CITY(
	Id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ZipCode INT NOT NULL
		CHECK(LENGTH(ZipCode) = 5),
	CityName VARCHAR(60) NOT NULL 
		CHECK(LENGTH(CityName) > 0),	
	CONSTRAINT uq_CITY UNIQUE KEY(ZipCode, CityName)
);

CREATE TABLE BRAND(
	Id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	BrandName VARCHAR(50) NOT NULL UNIQUE,
		CHECK(LENGTH(BrandName) > 0)

);

CREATE TABLE MODEL(
	Id BIGINT NOT NULL AUTO_INCREMENT,
	ModelName VARCHAR(50) NOT NULL
		CHECK(LENGTH(ModelName) > 0),
	BrandId BIGINT NOT NULL,
	CONSTRAINT fk_model_brand FOREIGN KEY(BrandId) REFERENCES CarDelership_DB.BRAND(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY(Id, BrandId)
);

CREATE TABLE `USER`(
	Id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	FirstName VARCHAR(60) NOT NULL,
	LastName VARCHAR(60) NOT NULL,
	DateOfBirth DATE NULL,
	Gender ENUM('MALE','FEMALE') NOT NULL,
	CityId BIGINT NOT NULL,
        CONSTRAINT fk_useraccount_city FOREIGN KEY(CityId) REFERENCES CarDelership_DB.CITY(Id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE USER_PROFILE(
	Email VARCHAR(100) PRIMARY KEY NOT NULL,
	`Password` VARCHAR(100) NOT NULL
		CHECK(LENGTH(`Password`) >= 7),
	UserId BIGINT NOT NULL,
	CONSTRAINT fk_userprofile_useraccount FOREIGN KEY(UserId) REFERENCES CarDelership_DB.USER(Id) ON UPDATE CASCADE ON DELETE CASCADE
	
	
);

CREATE TABLE BUSINESS_UNIT(
	Id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(200) NOT NULL
		CHECK(LENGTH(`Name`) > 0),
	CompanyRegNum VARCHAR(8) NOT NULL UNIQUE
		CHECK(LENGTH(CompanyRegNum) = 8 AND (CompanyRegNum REGEXP '^[0-9]{8}$')),
	TaxId VARCHAR(9) NOT NULL UNIQUE
		CHECK(LENGTH(TaxId) = 9 AND (TaxId REGEXP '^[0-9]{9}$')),
	Address VARCHAR(200) NOT NULL,	
	Phone VARCHAR(11) NULL,
		CHECK((Phone REGEXP '^[0-9]{3}/[0-9]{3}-[0-9]{3}$') OR (Phone IS NULL)),
	Email VARCHAR(100) NULL,
	CityId BIGINT NOT NULL,
	CONSTRAINT fk_buss_city FOREIGN KEY(CityId) REFERENCES CarDelership_DB.CITY(Id) ON UPDATE CASCADE ON DELETE RESTRICT	
);

CREATE TABLE VEHICLE(
	Id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ViNumber VARCHAR(17) NOT NULL UNIQUE,
	BodyType ENUM('LIMUZINA','HECBEK','KARAVAN','KUPE','KABRIOLET','MONOVOLUMEN','SUV','PICKUP') NOT NULL,
	EngDispl INT NOT NULL DEFAULT 0
		CHECK(EngDispl >= 0),
	EngPowerKW INT NOT NULL DEFAULT 0
		CHECK(EngPowerKW >= 0),
	YearOfProd INT NOT NULL,
	FuelType ENUM('BENZIN','DIZEL','HIBRIDNIPOGON','ELEKTRICNIPOGON') NOT NULL,
	Price DECIMAL(12,2) NOT NULL DEFAULT 0
		CHECK(Price >= 0),
	Currency ENUM('DIN','EUR','USD') NOT NULL DEFAULT 'DIN',
	ModelId BIGINT NOT NULL,
	BusinessUId BIGINT NOT NULL,
	CONSTRAINT fk_vehicle_businessUnit FOREIGN KEY(BusinessUId) REFERENCES CarDelership_DB.BUSINESS_UNIT(Id) ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT fk_vehicle_model FOREIGN KEY(ModelId) REFERENCES CarDelership_DB.MODEL(Id) ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT uq_vehicle UNIQUE KEY(ViNumber)	
);

CREATE TABLE EQUIPMENT(
	Id BIGINT NOT NULL AUTO_INCREMENT,
	BrandId BIGINT NOT NULL,
	`Name` VARCHAR(100) NOT NULL,
	Price DECIMAL(12,2) NOT NULL DEFAULT 0
		CHECK(Price >= 0),
	Currency ENUM('DIN','EUR','USD') NOT NULL DEFAULT 'DIN',
	
	CONSTRAINT fk_equipment_brand FOREIGN KEY(BrandId) REFERENCES CarDelership_DB.BRAND(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY(Id, BrandId),	
	CONSTRAINT uq_quipment UNIQUE KEY(BrandId, `Name`)
);

CREATE TABLE CUSTOMER(
	Id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(200) NOT NULL
		CHECK(LENGTH(`Name`) > 0),
	CompanyName VARCHAR(200) NULL,
	Address VARCHAR(200) NOT NULL,
	Phone VARCHAR(11) NOT NULL,
		CHECK(Phone REGEXP '^[0-9]{3}/[0-9]{3}-[0-9]{3}$'),
	Email VARCHAR(100) NULL	
);

CREATE TABLE PURCHASE_ORDER(
	PONumber BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	PurchaseDate DATE NOT NULL,
	CustomerId BIGINT NOT NULL,
	VehicleId BIGINT NOT NULL,
	SalesPersonId BIGINT NOT NULL,
	
	CONSTRAINT fk_purchaseOrder_customer FOREIGN KEY(CustomerId) REFERENCES CarDelership_DB.CUSTOMER(Id) ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT fk_purchaseOrder_vehicle FOREIGN KEY(VehicleId) REFERENCES CarDelership_DB.VEHICLE(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT fk_purchaseOrder_user FOREIGN KEY(SalesPersonId) REFERENCES CarDelership_DB.USER(Id) ON UPDATE CASCADE ON DELETE RESTRICT
) AUTO_INCREMENT = 10000;

CREATE TABLE PURCHASE_ORDER_ITEM(
	
	PONumber BIGINT NOT NULL,
	OrdinalNumber BIGINT NOT NULL,
	EquipmentId BIGINT NOT NULL,
	Quantity INT NOT NULL DEFAULT 1
		CHECK(Quantity >= 1),
	
	CONSTRAINT fk_orderItem_purchaseOrder FOREIGN KEY(PONumber) REFERENCES CarDelership_DB.PURCHASE_ORDER(PONumber) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_orderItem_equipment FOREIGN KEY(EquipmentId) REFERENCES CarDelership_DB.EQUIPMENT(Id) ON UPDATE CASCADE ON DELETE RESTRICT,
	PRIMARY KEY(PONumber, OrdinalNumber)
);



